#pragma once

#include <cstddef>
#include <string>

// DictionaryStore — binary-search lookup against dictionary.idx / dictionary.dat on the SD card.
//
// Files live at /dictionary.idx and /dictionary.dat in the SD card root.
// Both files are generated by scripts/build_dictionary.py from dictionary.csv.
//
// Index file format (dictionary.idx):
//   Header: magic[4]='DCTI' + version[1] + entry_count[4 LE] + word_field_size[1] = 10 bytes
//   Each entry (40 bytes): word_lower[32, null-padded] + dat_offset[4 LE] + dat_length[4 LE]
//   Entries are sorted alphabetically — enables O(log n) binary search via FsFile::seek().
//
// Data file format (dictionary.dat):
//   Per word: def_count[1] + { wt_len[1] + wordtype[N] + def_len[2 LE] + def_text[N] } * def_count

namespace DictionaryStore {

static constexpr char IDX_PATH[] = "/dictionary.idx";
static constexpr char DAT_PATH[] = "/dictionary.dat";

// Returns true if dictionary.idx exists on the SD card.
bool isAvailable();

// Look up `word` (case-insensitive, punctuation stripped automatically).
// On success writes a null-terminated formatted definition into outBuf and returns true.
// On failure (word not found, files missing) returns false and leaves outBuf unchanged.
// outBufSize should be at least 1024 bytes.
// If outFoundWord / outFoundWordSize are provided, the actual matched key (which may be a
// stemmed form, e.g. "negotiator" for input "negotiators") is written into outFoundWord.
bool lookup(const std::string& word, char* outBuf, size_t outBufSize,
            char* outFoundWord = nullptr, size_t outFoundWordSize = 0);

}  // namespace DictionaryStore
